# Generated by Django 4.2.3 on 2023-07-30 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shaba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shaba_number', models.CharField(max_length=24, unique=True)),
                ('bank_name', models.CharField(max_length=24)),
                ('full_name', models.CharField(max_length=24)),
                ('active_link', models.CharField(max_length=128, unique=True, verbose_name='لینک ارسال شده')),
                ('verified', models.BooleanField(default=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.wallet')),
            ],
            options={
                'verbose_name': 'shaba',
                'verbose_name_plural': 'shaba',
            },
        ),
    ]
